### ISSUE TITLE
qemu run errors()

### ISSUE THREAD

**Issue by bigmagic123** [T-head-Semi/qemu#1]
I want build qemu and run nuttx, And I have installed the environment.

build qemu
```
../configure --disable-werror --prefix=$RISCV/thead_qemu --disable-vnc --disable-sdl --disable-sdl-image --target-list=riscv32-softmmu,riscv64-softmmu && make -j8 && make install
```
compile and run nuttx

```
./tools/configure.sh -l smartl-c906:nsh

make

~/thead_qemu/bin/qemu-system-riscv64 -M smarth -cpu c906 -kernel nuttx -nographic
qemu-system-riscv64: ../hw/core/qdev.c:414: qdev_assert_realized_properly_cb: Assertion `dev->parent_bus || !dc->bus_type' failed.
?????? (??????????)
```

Why can't I use qemu normally?

**Comment by 0xcdef** [comment]
Got same problem....
but seems 'riscv64-softmmu' platform is not fully supported yet.
for bare metal running, you can try something like:
`./qemu-system-riscv64 -M virt -cpu c910 -bios nuttx.elf -nographic`
P.S, make sure to build 'nuttx.elf' following address mapping of virt/opensbi
or you can make nuttx.elf as payload of opensbi

refer to 'virt' machine definitons for kinds of peripherals.

**Comment by romanheros** [comment]
> I want build qemu and run nuttx, And I have installed the environment.
> 
> build qemu
> 
> ```
> ../configure --disable-werror --prefix=$RISCV/thead_qemu --disable-vnc --disable-sdl --disable-sdl-image --target-list=riscv32-softmmu,riscv64-softmmu && make -j8 && make install
> ```
> 
> compile and run nuttx
> 
> ```
> ./tools/configure.sh -l smartl-c906:nsh
> 
> make
> 
> ~/thead_qemu/bin/qemu-system-riscv64 -M smarth -cpu c906 -kernel nuttx -nographic
> qemu-system-riscv64: ../hw/core/qdev.c:414: qdev_assert_realized_properly_cb: Assertion `dev->parent_bus || !dc->bus_type' failed.
> ?????? (??????????)
> ```
> 
> Why can't I use qemu normally?

I have fixed this problem with the new merge
