### ISSUE TITLE
No smart_card machine?

### ISSUE THREAD

**Issue by JiaDuo** [T-head-Semi/qemu#2]
I download qemu binary, I see the smart_card Board,But this is not exist in this porject.

> $ ./riscv32-softmmu/qemu-system-riscv32 -M help
Supported machines are:
none                 empty machine
opentitan            RISC-V Board compatible with OpenTitan
sifive_e             RISC-V Board compatible with SiFive E SDK
sifive_u             RISC-V Board compatible with SiFive U SDK
smartl               RISC-V smartl
spike                RISC-V Spike board (default)
virt                 RISC-V VirtIO board

>D:\software\C-Sky\workspace-cds>..\CDS\qemu\qemu-system-cskyv1.exe -M help
Supported machines are:
deimos               CSKY deimos
dummyh               CSKY dummyh
hobbit1_2            CSKY hobbit1_2
none                 empty machine
smart_card           CSKY smart_card
smarth               CSKY smarth
smartl               CSKY smartl
trilobite            CSKY trilobite
trilobite_v2         CSKY trilobite_v2
virt                 C-SKY QEMU virt machine
yunvoice_v2          CSKY yunvoice_v2

**Comment by romanheros** [comment]
For RISC-V, QEMU doesn't implement the smart_card. For C-SKY, there is a smart_card marchine. I have pushed it recently.
